github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-midnight
gfm_quirks: paragraph_end
title: Untitled self-indulgent website
description: Website for George H. Williams
google_analytics: G-BXZ9DWM6SS
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
